font:
  size: 18.0
  normal:
    family: Iosevka Nerd Font Mono
    style: Regular
mouse:
  hints:
    launcher:
      # This depends on your OS, on Mac it’s `open`
      program: open
    mods: Command

scrolling:
  # How many lines of scrollback to keep,
  # '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line
  # scrolled when scrollback is enabled (history > 0).
  multiplier: 3

  # Faux Scrolling
  #
  # The `faux_multiplier` setting controls the number
  # of lines the terminal should scroll when the alternate
  # screen buffer is active. This is used to allow mouse
  # scrolling for applications like `man`.
  #
  # To disable this completely, set `faux_multiplier` to 0.
  faux_multiplier: 3

  # Automatically scroll to the bottom when new text is written
  # to the terminal.
  auto_scroll: false

# github Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0x0d1117'
    foreground: '0xb3b1ad'

  # Normal colors
  normal:
    black:   '0x484f58'
    red:     '0xff7b72'
    green:   '0x3fb950'
    yellow:  '0xd29922'
    blue:    '0x58a6ff'
    magenta: '0xbc8cff'
    cyan:    '0x39c5cf'
    white:   '0xb1bac4'

  # Bright colors
  bright:
    black:   '0x6e7681'
    red:     '0xffa198'
    green:   '0x56d364'
    yellow:  '0xe3b341'
    blue:    '0x79c0ff'
    magenta: '0xd2a8ff'
    cyan:    '0x56d4dd'
    white:   '0xf0f6fc'

  indexed_colors:
    - { index: 16, color: '0xd18616' }
    - { index: 17, color: '0xffa198' }
